// Products & Campaigns mock data

export const PRODUCTS_MOCK = [
  {
    id: 1,
    name: 'Samsung Galaxy A15',
    sku: 'SKU-2041',
    category: 'Smartphones',
    base_price: 42999,
    ai_updated_at: '2026-05-16T10:22:00Z',
    ai_price_change: -12,
    inventory: { Karachi: 24, Lahore: 4, Islamabad: 11, Peshawar: 0 },
    total_stock: 39,
    status: 'low_stock',
  },
  {
    id: 2,
    name: 'Xiaomi Redmi Note 13',
    sku: 'SKU-1892',
    category: 'Smartphones',
    base_price: 36500,
    ai_updated_at: null,
    ai_price_change: null,
    inventory: { Karachi: 58, Lahore: 33, Islamabad: 27, Peshawar: 14 },
    total_stock: 132,
    status: 'healthy',
  },
  {
    id: 3,
    name: 'HP Pavilion Laptop 15',
    sku: 'SKU-3301',
    category: 'Laptops',
    base_price: 128000,
    ai_updated_at: '2026-05-15T14:05:00Z',
    ai_price_change: +5,
    inventory: { Karachi: 8, Lahore: 6, Islamabad: 3, Peshawar: 2 },
    total_stock: 19,
    status: 'low_stock',
  },
  {
    id: 4,
    name: 'Sony WH-1000XM5 Headphones',
    sku: 'SKU-4412',
    category: 'Audio',
    base_price: 89000,
    ai_updated_at: null,
    ai_price_change: null,
    inventory: { Karachi: 0, Lahore: 0, Islamabad: 0, Peshawar: 0 },
    total_stock: 0,
    status: 'out_of_stock',
  },
  {
    id: 5,
    name: 'Apple iPhone 15',
    sku: 'SKU-5500',
    category: 'Smartphones',
    base_price: 249000,
    ai_updated_at: '2026-05-16T08:00:00Z',
    ai_price_change: -3,
    inventory: { Karachi: 15, Lahore: 9, Islamabad: 7, Peshawar: 3 },
    total_stock: 34,
    status: 'healthy',
  },
  {
    id: 6,
    name: 'Logitech MX Master 3S',
    sku: 'SKU-6610',
    category: 'Accessories',
    base_price: 22000,
    ai_updated_at: null,
    ai_price_change: null,
    inventory: { Karachi: 44, Lahore: 22, Islamabad: 18, Peshawar: 9 },
    total_stock: 93,
    status: 'healthy',
  },
];

export const CAMPAIGNS_MOCK = [
  {
    id: 1,
    name: 'Karachi Summer Surge',
    coupon_code: 'KHI-SURGE18',
    discount_percent: 18,
    region: 'Karachi',
    status: 'active',
    ai_generated: true,
    projected_impact: '+₨ 82,000',
    start_date: '2026-05-15',
    orders_used: 47,
  },
  {
    id: 2,
    name: 'Lahore Velocity Boost',
    coupon_code: 'LHR-BOOST12',
    discount_percent: 12,
    region: 'Lahore',
    status: 'active',
    ai_generated: true,
    projected_impact: '+23% velocity',
    start_date: '2026-05-14',
    orders_used: 89,
  },
  {
    id: 3,
    name: 'Eid Mega Sale',
    coupon_code: 'EID-MEGA20',
    discount_percent: 20,
    region: 'All Regions',
    status: 'scheduled',
    ai_generated: false,
    projected_impact: 'TBD',
    start_date: '2026-05-20',
    orders_used: 0,
  },
  {
    id: 4,
    name: 'Islamabad Flash Deal',
    coupon_code: 'ISB-FLASH15',
    discount_percent: 15,
    region: 'Islamabad',
    status: 'ended',
    ai_generated: true,
    projected_impact: '+₨ 44,000',
    start_date: '2026-05-10',
    orders_used: 128,
  },
];

// Extend mock router
export const getMockResponseExtended = (url: string): any | null => {
  if (url.includes('/products')) return PRODUCTS_MOCK;
  if (url.includes('/campaigns')) return CAMPAIGNS_MOCK;
  return null;
};
